"""Workflow state management using TypedDict.

This module defines the WorkflowState TypedDict that represents the
state object passed through the LangGraph workflow. The state is immutable
where possible and validated at each workflow step.

Example:
    ```python
    from src.graph.state import WorkflowState
    from langchain_core.messages import HumanMessage
    
    initial_state: WorkflowState = {
        "messages": [HumanMessage(content="Analyze competitors")],
        "plan": None,
        "collected_data": None,
        "insights": None,
        "report": None,
        "retry_count": 0,
        "current_task": None,
        "validation_errors": []
    }
    ```
"""

from typing import Annotated, Any, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class WorkflowState(TypedDict, total=False):
    """State object for the competitor analysis workflow.
    
    This TypedDict defines the structure of state passed through the
    LangGraph workflow. All fields are optional (total=False) to allow
    incremental state building, but required fields should be initialized
    before use.
    
    Attributes:
        messages: List of messages in the conversation, annotated with
            LangGraph's add_messages reducer for automatic message merging
        plan: Optional dictionary containing the execution plan generated
            by the planner agent (tasks, sources, strategy)
        collected_data: Optional dictionary containing competitor data
            collected by the data collector agent
        insights: Optional dictionary containing business insights and
            SWOT analysis generated by the insight agent
        report: Optional string containing the final formatted report
            generated by the report agent
        export_paths: Optional dictionary mapping export types to file paths
            (e.g., {"pdf": "path/to/file.pdf", "swot_diagram": "path/to/diagram.png"})
        retry_count: Integer tracking the number of retry attempts (default: 0)
        current_task: Optional string indicating the current task being
            executed in the workflow
        validation_errors: List of validation error messages encountered
            during workflow execution
    """
    
    messages: Annotated[list[BaseMessage], add_messages]
    plan: dict[str, Any] | None
    collected_data: dict[str, Any] | None
    insights: dict[str, Any] | None
    report: str | None
    export_paths: dict[str, str] | None
    retry_count: int
    current_task: str | None
    validation_errors: list[str]


def create_initial_state(
    initial_message: str | BaseMessage | None = None
) -> WorkflowState:
    """Create an initial workflow state with default values.
    
    Helper function to create a properly initialized WorkflowState with
    all required fields set to their default values. This ensures type
    safety and prevents missing field errors.
    
    Args:
        initial_message: Optional initial message to include in the state.
            Can be a string (will be converted to HumanMessage) or a
            BaseMessage instance.
    
    Returns:
        WorkflowState dictionary with all fields initialized to defaults
        
    Example:
        ```python
        from src.graph.state import create_initial_state
        
        state = create_initial_state("Analyze competitors in the SaaS market")
        assert state["retry_count"] == 0
        assert len(state["messages"]) == 1
        ```
    """
    from langchain_core.messages import HumanMessage
    
    messages: list[BaseMessage] = []
    if initial_message:
        if isinstance(initial_message, str):
            messages = [HumanMessage(content=initial_message)]
        else:
            messages = [initial_message]
    
    return WorkflowState(
        messages=messages,
        plan=None,
        collected_data=None,
        insights=None,
        report=None,
        export_paths=None,
        retry_count=0,
        current_task=None,
        validation_errors=[],
    )
