"""Plan model for task planning.

This module defines the Plan Pydantic model that represents the execution
plan generated by the planner agent. The plan breaks down user requests
into actionable tasks with search strategies and requirements.

Example:
    ```python
    from src.models.plan_model import Plan
    
    plan = Plan(
        tasks=["Collect pricing data", "Analyze competitors"],
        preferred_sources=["web search", "official site"],
        minimum_results=6,
        search_strategy="comprehensive"
    )
    ```
"""

from typing import Any

from pydantic import BaseModel, Field, field_validator


class Plan(BaseModel):
    """Task plan generated by planner agent.
    
    This model represents the execution plan created by the planner agent
    to break down user requests into actionable tasks. It includes search
    strategies, source preferences, and minimum result requirements.
    
    Attributes:
        tasks: List of tasks to execute in the workflow
        preferred_sources: List of preferred data sources (e.g., "web search")
        minimum_results: Minimum number of results required (must be >= 1)
        search_strategy: Search strategy to use (e.g., "comprehensive", "focused")
    """
    
    model_config = {"extra": "forbid"}
    
    tasks: list[str] = Field(
        ...,
        description="List of tasks to execute",
        min_length=1,
    )
    
    preferred_sources: list[str] = Field(
        default_factory=list,
        description="List of preferred data sources",
    )
    
    minimum_results: int = Field(
        default=4,
        description="Minimum number of results required",
        ge=1,
        le=100,
    )
    
    search_strategy: str = Field(
        default="comprehensive",
        description="Search strategy to use",
        min_length=1,
    )
    
    @field_validator("tasks")
    @classmethod
    def validate_tasks(cls, value: list[str]) -> list[str]:
        """Validate that tasks list is not empty and contains non-empty strings.
        
        Args:
            value: List of task strings to validate
            
        Returns:
            Validated list of task strings
            
        Raises:
            ValueError: If tasks list is empty or contains empty strings
        """
        if not value:
            raise ValueError("Tasks list cannot be empty")
        
        filtered_tasks = [task.strip() for task in value if task.strip()]
        if not filtered_tasks:
            raise ValueError("Tasks list cannot contain only empty strings")
        
        return filtered_tasks
    
    @field_validator("search_strategy")
    @classmethod
    def validate_search_strategy(cls, value: str) -> str:
        """Validate search strategy is not empty.
        
        Args:
            value: Search strategy string to validate
            
        Returns:
            Validated search strategy string
        """
        if not value or not value.strip():
            raise ValueError("Search strategy cannot be empty")
        return value.strip()
